name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "fabioalmeida08-us-east-1-terraform-pipeline"
      aws-assume-role-arn: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      aws-lock-dynamodb-table: "fabioalmeida08-us-east-1-terraform-lock"
    secrets: inherit  # Adicione esta linha
